#!/usr/bin/env bash

set -e

print_info()      { printf "\n\e[0;35m $1\e[0m\n\n"; }      # Purple
print_question()  { printf "\e[0;33m  [?] $1\e[0m"; }       # Yellow
print_success()   { printf "\e[0;32m  [✔] $1\e[0m\n"; }     # Green
print_error()     { printf "\e[0;31m  [✖] $1 $2\e[0m\n"; }  # Red
print_result()    {
    [ $1 -eq 0 ] && print_success "$2" || print_error "$2"
    [ "$3" == "true" ] && [ $1 -ne 0 ] && exit
}

if test ! $(xcode-select -p)
then
  print_info "Installing Xcode Command Line Tools"
  xcode-select --install
  print_result $? "Installing Xcode Command Line Tools"
fi

if test ! $(which brew)
then
    print_info "Installing Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    print_result $? "Installing Homebrew"
fi

print_success "Success!"